### ISSUE TITLE
Can it handle private repo?  How about conflict ?

### ISSUE THREAD

**Issue by Fred-Vatin** [iamssen/copy-github-directory#14]
Hi,

1. Can it copy folder from private repo ?
2. How does it handle conflict if a downloaded file already exists in the working dir ? Is there an option to skip it ?

**Comment by iamssen** [comment]
@Fred-Vatin 1. If `GITHUB_TOKEN` is set in your env, the private repo also work. (refer to this code https://github.com/rocket-hangar/copy-github-directory/blob/master/packages/src/copy-github-directory/index.ts#L76)
2. It will not work on non-empty folders. so, conflict does not occur.
